### ISSUE TITLE
plug in is broken in kodi 

### ISSUE THREAD

**Issue by nickherea** [divingmule/plugin.video.on_aol#2]
16:33:20 T:2700  NOTICE: [addon.on_aol-1.0.2]: Request URL: http://on.aol.com
16:33:20 T:2700  NOTICE: [addon.on_aol-1.0.2]: ResponseInfo: Content-Type: text/html; charset=utf-8

```
                                        Set-Cookie: aol.aolon.user={"token":"ACCT-AN-hks3vnp92fvkm4bxp0v3tb9dbqlnfhc1cbzg01jd9f5zjg3nf18n"}; Max-Age=1001308; Expires=Wed, 28 Oct 2015 11:42:01 UTC; Path=/

                                        Set-Cookie: AOLON_BETA=1; Max-Age=28800; Expires=Sat, 17 Oct 2015 05:33:33 UTC; Path=/

                                        Set-Cookie: aol.aolon.anonymoususer={"token":"ACCT-AN-hks3vnp92fvkm4bxp0v3tb9dbqlnfhc1cbzg01jd9f5zjg3nf18n"}; Max-Age=1001308; Expires=Wed, 28 Oct 2015 11:42:01 UTC; Path=/

                                        Content-Length: 580488

                                        Connection: keep-alive

                                        Set-Cookie: NSC_po-bpm*80=ffffffff35ac720845525d5f4f58455e445a4a423660;path=/;httponly
```

16:33:22 T:2700   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\plugin.video.on_aol\default.py", line 471, in <module>
                                                get_home_page()
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\plugin.video.on_aol\default.py", line 137, in get_home_page
                                                items = cache.cacheFunction(cache_home_page)
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib\StorageServer.py", line 563, in cacheFunction
                                                ret_val = funct(*args)
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\plugin.video.on_aol\default.py", line 132, in cache_home_page
                                                return get_page_items(base_url)
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\plugin.video.on_aol\default.py", line 75, in get_page_items
                                                for i in soup.noscript('a'):
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
16:33:22 T:5884   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.on_aol/
16:33:22 T:5884   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.on_aol/) failed
16:33:22 T:5608  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by divingmule** [comment]
Working on reviving this add-on, stay tuned.
